---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Embedded Ansible - List Playbooks
    name: embedded_ansible_list_playbooks
    inherits: 
    description: Lists playbooks by repository (expects "dialog_ansible_repo_id")
  fields:
  - execute:
      value: embedded_ansible_list_playbooks
