---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Embedded Ansible - List Playbooks
    name: list_embedded_ansible_playbook_ids
    inherits: 
    description: Lists playbooks by repository (expects "dialog_ansible_repo_id")
  fields:
  - execute:
      value: list_embedded_ansible_playbook_ids
